### ISSUE TITLE
denormalize_spec

### ISSUE THREAD

**Issue by yinhao0214** [Yablon/auorange#1]
def denormalize_spec(spectrogram):
  return np.exp(spectrogram) - 1. / 10000
应该改成
return (np.exp(spectrogram) - 1.) / 10000 吧？
ps 我试了两种，结果几乎一样

**Comment by Yablon** [comment]
@FanhuaandLuomu Sorry, I didn't see your issue until now. I fixed this a few days ago. Thank you for your kindness and sorry again.
