### ISSUE TITLE
Why the prediction need original wavdata?

### ISSUE THREAD

**Issue by JohnHerry** [Yablon/auorange#2]
Hi,

I noticed the code as follows"

```
mel_spec = audio_processor.mel_spectrogram(wav_data)

audio, pred, error = audio_processor.lpc_audio(mel_spec, wav_data)
```

So the audio processor in this project need not only mel but also original wav_data to predict the audio wave?

**Comment by zzw922cn** [comment]
here is for calculating difference between predicted audio and raw audio.

**Comment by Yablon** [comment]
@JohnHerry sorry for the late reply. You can @me if there is no response.
Yes, we need not only mel, but original wav_data to predict the audio wave.

Every point of sample in pred, is calculated by lpc coefficients from mel_spec and the former real points from wav_data.

Let the lpc coefficients be

<a href="https://www.codecogs.com/eqnedit.php?latex=a_i(i=0,1,...,n)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?a_i(i=0,1,...,n)" title="a_i(i=0,1,...,n)" /></a>

n is lpc order.
and the wav_data points are
<a href="https://www.codecogs.com/eqnedit.php?latex=s_i(i=0,1,...,m)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?s_i(i=0,1,...,m)" title="s_i(i=0,1,...,m)" /></a>
m is  lengths of wav_data.

for the jth point in pred, it is calculated as follows:

<a href="https://www.codecogs.com/eqnedit.php?latex=pred_j&space;=&space;\Sigma&space;a_i&space;s_{j&space;-&space;i&space;-&space;1}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?pred_j&space;=&space;\Sigma&space;a_i&space;s_{j&space;-&space;i&space;-&space;1}" title="pred_j = \Sigma a_i s_{j - i - 1}" /></a>
where i is from 0 to lpc_order.

Lpc prediction in this repository is for autoregressive speech synthesis vocoders. In inference, we can get former points and use lpc coefficients to predict next sample candidate, which helps neural vocoder predict the real next sample.

**Comment by Yablon** [comment]
@zzw922cn Thank you for your reply

**Comment by JohnHerry** [comment]
> @zzw922cn Thank you for your reply

Thanks for the help, @Yablon @zzw922cn
